"""empty message

Revision ID: 9aec744a6b98
Revises: 5638379d1820
Create Date: 2021-08-20 13:31:22.622772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aec744a6b98'
down_revision = '5638379d1820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('form_id', sa.Integer(), nullable=True))
    op.drop_constraint('fields_form_fkey', 'fields', type_='foreignkey')
    op.create_foreign_key(None, 'fields', 'forms', ['form_id'], ['id'])
    op.drop_column('fields', 'form')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('form', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'fields', type_='foreignkey')
    op.create_foreign_key('fields_form_fkey', 'fields', 'forms', ['form'], ['id'])
    op.drop_column('fields', 'form_id')
    # ### end Alembic commands ###
