"""empty message

Revision ID: 2453c767d036
Revises: d0c387e43ca4
Create Date: 2021-08-21 14:53:11.208418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2453c767d036'
down_revision = 'd0c387e43ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('forms_field_id_fkey', 'forms', type_='foreignkey')
    op.drop_column('forms', 'field_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('field_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('forms_field_id_fkey', 'forms', 'fields', ['field_id'], ['id'])
    # ### end Alembic commands ###
