"""empty message

Revision ID: d25f4d1b7ea0
Revises: 016e33f02c18
Create Date: 2021-08-19 20:07:22.834059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd25f4d1b7ea0'
down_revision = '016e33f02c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=55), nullable=True),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('placeholder', sa.String(length=255), nullable=True),
    sa.Column('instructions', sa.String(length=255), nullable=True),
    sa.Column('choices', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fields')
    # ### end Alembic commands ###
