"""empty message

Revision ID: 5638379d1820
Revises: b05fdd14ae4f
Create Date: 2021-08-20 13:27:06.301835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5638379d1820'
down_revision = 'b05fdd14ae4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('form', sa.Integer(), nullable=True))
    op.drop_constraint('fields_form_id_fkey', 'fields', type_='foreignkey')
    op.create_foreign_key(None, 'fields', 'forms', ['form'], ['id'])
    op.drop_column('fields', 'form_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('form_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'fields', type_='foreignkey')
    op.create_foreign_key('fields_form_id_fkey', 'fields', 'forms', ['form_id'], ['id'])
    op.drop_column('fields', 'form')
    # ### end Alembic commands ###
