"""empty message

Revision ID: 94f5eda37179
Revises: b3e721c02f48
Create Date: 2021-08-20 17:15:46.455809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94f5eda37179'
down_revision = 'b3e721c02f48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fields', 'label',
               existing_type=sa.VARCHAR(length=55),
               nullable=False)
    op.alter_column('forms', 'title',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('forms', 'title',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('fields', 'label',
               existing_type=sa.VARCHAR(length=55),
               nullable=True)
    # ### end Alembic commands ###
