"""empty message

Revision ID: 0dc78263d249
Revises: b8ec5632d693
Create Date: 2021-08-20 10:21:41.709451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dc78263d249'
down_revision = 'b8ec5632d693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fields_form_id_fkey', 'fields', type_='foreignkey')
    op.drop_column('fields', 'form_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('form_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('fields_form_id_fkey', 'fields', 'forms', ['form_id'], ['id'])
    # ### end Alembic commands ###
