"""empty message

Revision ID: eb2638a12baa
Revises: 4df12f583573
Create Date: 2021-08-22 23:31:25.835585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb2638a12baa'
down_revision = '4df12f583573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
