"""empty message

Revision ID: 4563136888fd
Revises: 0dc78263d249
Create Date: 2021-08-20 10:30:15.535756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4563136888fd'
down_revision = '0dc78263d249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('form_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'fields', 'forms', ['form_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fields', type_='foreignkey')
    op.drop_column('fields', 'form_id')
    # ### end Alembic commands ###
