"""empty message

Revision ID: b05fdd14ae4f
Revises: 4563136888fd
Create Date: 2021-08-20 10:34:08.171553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b05fdd14ae4f'
down_revision = '4563136888fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fields', 'label',
               existing_type=sa.VARCHAR(length=55),
               nullable=True)
    op.alter_column('fields', 'required',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fields', 'required',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('fields', 'label',
               existing_type=sa.VARCHAR(length=55),
               nullable=False)
    # ### end Alembic commands ###
