"""empty message

Revision ID: 016e33f02c18
Revises: fa590b961f4f
Create Date: 2021-08-19 20:05:34.180981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016e33f02c18'
down_revision = 'fa590b961f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('label_placement', sa.String(length=10), nullable=True))
    op.create_foreign_key(None, 'forms', 'users', ['owner_id'], ['id'])
    op.drop_column('forms', 'label_align')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('label_align', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'forms', type_='foreignkey')
    op.drop_column('forms', 'label_placement')
    # ### end Alembic commands ###
